name: flutter-passkeys
repository: https://github.com/corbado/flutter-passkeys
packages:
  - packages/**

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  format:
    description: Format Dart code.
    run: dart format .

  format:check:
    description: Check formatting of Dart code.
    run: dart format --output none --set-exit-if-changed .

  analyze:
    description: Analyze Dart code.
    run: dart analyze . --fatal-infos

  test:
    description: Run tests in a specific package.
    run: dart test
    exec:
      concurrency: 1
    packageFilters:
      dirExists:
        - test

  example-passkeys-web:
    description: Run passkeys example on web.
    run: |
      cd packages/passkeys/passkeys/example
      flutter run lib/main.dart -d chrome --web-browser-flag "--disable-web-security"

  example-passkeys-native:
    description: Run passkeys example on iOS or Android (you should start the emulator/simulator before you run this command).
    run: |
      cd packages/passkeys/passkeys/example
      flutter run lib/main.dart

  example-corbado_auth-native:
    description: Run corbado_auth example on iOS or Android (you should start the emulator/simulator before you run this command).
    run: |
      cd packages/corbado_auth/example
      flutter run lib/main.dart

  example-corbado_auth-web:
    description: Run corbado_auth example on web.
    run: |
      cd packages/corbado_auth/example
      flutter run lib/main.dart -d chrome --web-browser-flag "--disable-web-security"

  example-corbado_auth_firebase-native:
    description: Run corbado_auth_firebase example on iOS or Android (you should start the emulator/simulator before you run this command).
    run: |
      cd packages/corbado_auth_firebase/example
      flutter run lib/main.dart --dart-define=CORBADO_PROJECT_ID=pro-8751299119685489253

  build-passkeys-web-javascript:
    description: Build passkeys_web's javascript code and copy it to the example.
    run: |
      cd packages/passkeys/passkeys_web/javascript
      npm run build
      cp dist/bundle.js ../../passkeys/example/web/bundle.js

  deploy-example-passkeys-web:
    description: Deploy passkeys example to Vercel.
    run: |
      cd packages/passkeys/passkeys/example
      vercel pull
      vercel build --prod
      vercel deploy --prebuilt --prod

  deploy-example-corbado_auth-web:
    description: Deploy corbado_auth example to Vercel.
    run: |
      cd packages/corbado_auth/example
      vercel pull
      vercel build --prod
      vercel deploy --prebuilt --prod
