name: Deploy examples to Vercel
env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Deploy Next example to Vercel
        run: |
          cd packages/passkeys/passkeys/example
          vercel pull -t $VERCEL_TOKEN
          vercel build --prod -t $VERCEL_TOKEN
          vercel deploy --prebuilt --prod -t $VERCEL_TOKEN
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_PASSKEYS_EXAMPLE }}
