name: Build and Test Flutter App

on:
  push:
    branches:
      - main
      - automated-tests
  pull_request:
    branches:
      - main

jobs:
  build-test-android:
    name: Build and Test Flutter App on Android
    runs-on: macos-latest

    defaults:
      run:
        working-directory: packages/passkeys/passkeys/example

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'

      # Step 3: Install Node.js (for Appium)
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 4: Install Appium and Dependencies
      - name: Install Appium and Test Dependencies
        run: |
          npm install -g appium
          appium driver install --source=npm appium-flutter-driver
          appium driver install uiautomator2
          appium driver install --source npm appium-flutter-integration-driver 

      # Step 5: Install Dependencies
      - name: Install Flutter Dependencies
        run: |
          flutter pub get

      # Step 6: Set up Java (Java 17)
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 7: Start the Emulator
      - name: Set Up Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 35
          target: google_apis
          arch: x86_64
          profile: pixel_5
          script: |
            adb wait-for-device
            adb shell input keyevent 82 &  

      # Step 8: Build & run the App
      - name: Build & run Flutter App
        run: |
          flutter run lib/main.dart --dart-define=CORBADO_PROJECT_ID=pro-8751299119685489253 -d emulator-5554 --no-resident
          sleep 10
          adb shell am force-stop com.corbado.passkeys.pub

      # Step 9: Start Appium Server
      - name: Start Appium Server
        run: |
          nohup appium > appium.log 2>&1 &
          sleep 10

      # Step 10: Run Tests
      - name: Run Appium Tests
        run: |
          cd tests
          npm i
          node main.js ios

  build-test-ios:
    name: Build and Test Flutter App on iOS
    runs-on: macos-latest

    defaults:
      run:
        working-directory: packages/passkeys/passkeys/example

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'

      # Step 3: Install Node.js (for Appium)
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 4: Install Appium and Dependencies
      - name: Install Appium and Test Dependencies
        run: |
          npm install -g appium
          appium driver install --source=npm appium-flutter-driver
          appium driver install uiautomator2
          appium driver install --source npm appium-flutter-integration-driver 

      # Step 5: Install Dependencies
      - name: Install Flutter Dependencies
        run: flutter pub get

      # Step 6: Set up Xcode
      - name: Set Up Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
          sudo xcodebuild -license accept

      # Step 7: Launch the iOS Simulator
      - name: Launch iOS Simulator
        run: |
          xcrun simctl create "appiumTestDevice" "iPhone 16 Pro" "com.apple.CoreSimulator.SimRuntime.iOS-18-1"
          xcrun simctl boot "iPhone 16 Pro"

      # Step 8: Run the app
      - name: Run the App
        run: |
          flutter run lib/main.dart --dart-define=CORBADO_PROJECT_ID=pro-8751299119685489253 -d "iPhone 16 Pro" --no-resident
          sleep 10
          xcrun simctl terminate booted com.corbado.passkeys.pub

      # Step 9: Start Appium Server
      - name: Start Appium Server
        run: |
          nohup appium > appium.log 2>&1 & 
          sleep 10

      # Step 10: Run Tests
      - name: Run Appium Tests
        run: |
          cd tests
          npm i
          node main.js ios

      # Step 11: Print Appium Logs (if tests fail)
      - name: Print Appium Logs
        if: failure()
        run: |
          echo "Printing Appium logs..."
          cat appium.log
