name: Build and Test Flutter App

on:
  push:
    branches:
      - main
      - automated-tests
  pull_request:
    branches:
      - main

jobs:
  build-test-android:
    name: Build and Test Flutter App on Android
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: packages/passkeys/passkeys/example

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'

      # Step 3: Install Node.js (for Appium)
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 4: Install Appium and Dependencies
      - name: Install Appium and Test Dependencies
        run: |
          npm install -g appium
          appium driver install --source=npm appium-flutter-driver
          appium driver install uiautomator2
          appium driver install --source npm appium-flutter-integration-driver 

      # Step 5: Install Flutter Dependencies
      - name: Install Flutter Dependencies
        run: |
          flutter pub get

      # Step 6: Set up Java (Java 17)
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 7: Start Appium
      - name: Start Appium Server
        run: |
          appium > appium.log 2>&1 & 

      # Step 7: Start the Emulator
      - name: Set Up Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: google_apis
          arch: x86_64
          profile: Nexus 6
          emulator-options: "-no-audio -no-window -gpu swiftshader_indirect"
          script: |
            adb shell input keyevent 82 &  
            flutter build apk --debug
            adb install -r build/app/outputs/flutter-apk/app-debug.apk
            cd tests
            npm i
            node main.js android

